owner: putty182
repo: upptime

sites:
  - name: Plex
    url: $SITES_URL_PLEX
  - name: Media Storage
    url: $SITES_URL_STORAGE
    method: POST
    headers:
      - "Authorization: $SITES_URL_STORAGE_AUTHZ"
    __dangerous__body_down_if_text_missing: '"result": "AOK\n"'
  - name: Requests
    url: $SITES_URL_REQUESTS
  - name: Downloads
    url: $SITES_URL_DOWNLOADS
  - name: TV Manager
    url: $SITES_URL_TV_MANAGER
    headers:
      - "x-api-key: $SITES_URL_TV_MANAGER_AUTHZ"
  - name: Movie Manager
    url: $SITES_URL_MOVIE_MANAGER
    headers:
      - "x-api-key: $SITES_URL_MOVIE_MANAGER_AUTHZ"

status-website:
  cname: status.c17.in
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Upptime"
  introTitle: ""
  introMessage: ""
  navbar: []
