owner: putty182
repo: upptime

sites:
  - name: Plex
    url: $SITES_URL_PLEX
    maxResponseTime: 1000
  - name: Requests
    url: $SITES_URL_REQUESTS
    maxResponseTime: 1000
  - name: Media Fetcher
    url: $SITES_URL_DOWNLOADS
    maxResponseTime: 1000
  - name: TV Manager
    url: $SITES_URL_TV_MANAGER
    maxResponseTime: 1000
  - name: Movie Manager
    url: $SITES_URL_MOVIE_MANAGER
    maxResponseTime: 1000
  - name: Storage
    url: $SITES_URL_STORAGE
    maxResponseTime: 1000
    method: POST
    headers:
      - "$SITES_AUTHZ_STORAGE"
    __dangerous__body_down_if_text_missing: '"result": "AOK\n"'

status-website:
  cname: status.c17.in
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Upptime"
  introTitle: ""
  introMessage: ""
  navbar: []
