owner: putty182
repo: upptime

sites:
  - name: Plex
    url: $SITES_URL_PLEX
    maxResponseTime: 2000
  - name: Requests
    url: $SITES_URL_REQUESTS
    maxResponseTime: 2000
  - name: Media Fetcher
    url: $SITES_URL_DOWNLOADS
    maxResponseTime: 2000
  - name: TV Manager
    url: $SITES_URL_TV_MANAGER
    maxResponseTime: 2000
  - name: Movie Manager
    url: $SITES_URL_MOVIE_MANAGER
    maxResponseTime: 2000

status-website:
  cname: status.c17.in
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Upptime"
  introTitle: ""
  introMessage: ""
  navbar: []
